name: hemicycle
description: Draw a semi-circle dotted representation. It is designed for displaying groups in an Assembly per sector, or individual votes.
version: 0.3.1
homepage:
repository: https://github.com/1278real/hemicycle

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0