name: hemicycle
description: Draw a semi-circle assembly representation.
version: 0.0.5
homepage:
repository: https://github.com/1278real/hemicycle

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.0.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: solutions.1278reeal.hemicycle
        pluginClass: HemicyclePlugin
      ios:
        pluginClass: HemicyclePlugin